### ISSUE TITLE
Gruber thesis has two NTRs with 1 auxiliary, but I have 4. 

### ISSUE THREAD

**Issue by ndattani** [HPQC-LABS/Book_About_Quadratization#28]
- [x] NTR-ABCG2 comes from pg. 8 of 2016 ABCG discrete applied mathematics, but is not in the thesis. (thesis does NOT say it has only prime factorizations, so it should have NTR-ABCG-2 ?)
- [x] Add the form of 2016 paper as an "alternative form" of ABCG-2.
- [x] Is NTR-GBP really isomorphic?

**Comment by erodriguezheck** [comment]
I have realized that NTR-ABCG2 and NTR-KZFD are both particular cases of a more general expression (see section NTR-ABCG2, Alternate Forms). I guess at some point both NTR-KZFD and NTR-ABCG2 should be unified in a single section? 
Also, NTR-ABCG2 probably does not appear in Gruber's thesis because it is not prime. Even if he does not say this explicitly, I think he implicitly generated the list while looking for prime quadratizations.

**Comment by erodriguezheck** [comment]
NTR-GBP is indeed isomorphic to NTR-ABCG (change the roles of b1 and b3, and flip ba). I have added a comment in NTR-GBP. I guess it should be unified under NTR-ABCG which is more general? 

This means that in the end the book would contain the two prime quadratizations for NTR with 1 auxiliary variable mentioned in ABCG.
